//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Familie
    {
        public Familie()
        {
            this.Persoon = new HashSet<Persoon>();
            this.Persoon1 = new HashSet<Persoon>();
        }
    
        public int FamilieID { get; set; }
        public string FamilieNaam { get; set; }
    
        public virtual ICollection<Persoon> Persoon { get; set; }
        public virtual ICollection<Persoon> Persoon1 { get; set; }
    }
}
