//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kennis
    {
        public Kennis()
        {
            this.Persoon1 = new HashSet<Persoon>();
        }
    
        public int KennisID { get; set; }
        public string Naam { get; set; }
        public string Achternaam { get; set; }
        public string Email { get; set; }
        public Nullable<int> Telefoonnummer { get; set; }
        public Nullable<int> PersoonID { get; set; }
    
        public virtual Persoon Persoon { get; set; }
        public virtual ICollection<Persoon> Persoon1 { get; set; }
    }
}
