//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persoon
    {
        public Persoon()
        {
            this.Kennis = new HashSet<Kennis>();
        }
    
        public int PersoonID { get; set; }
        public string Naam { get; set; }
        public string Achternaam { get; set; }
        public Nullable<int> Telefoonnummer { get; set; }
        public int FamilieID { get; set; }
        public string E_mail { get; set; }
        public Nullable<int> KennisID { get; set; }
        public string Loginnaam { get; set; }
        public string Wachtwoord { get; set; }
    
        public virtual Familie Familie { get; set; }
        public virtual Familie Familie1 { get; set; }
        public virtual ICollection<Kennis> Kennis { get; set; }
        public virtual Kennis Kennis1 { get; set; }
    }
}
